---

- name: RPM PERCONA REPOSITORY
  yum: >
    state=present
    name=http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm

- name: installing server-shared
  yum: state=removed name=mysql* disablerepo=percona

- name: remove original lock file
  file: state=absent dest=/var/lock/subsys/mysql

- file: state=absent dest=/var/lib/mysql/ibdata1
- file: state=absent dest=/var/lib/mysql/ib_logfile0
- file: state=absent dest=/var/lib/mysql/ib_logfile1

- name: installing server-shared
  yum: state=latest name=Percona-Server-shared-56 enablerepo=percona

- name: installing server
  yum: state=latest name=Percona-Server-server-56 enablerepo=percona

- name: installing server-shared-compat
  yum: state=latest name=Percona-Server-shared-compat enablerepo=percona

- name: configure MySQL with my.conf
  copy: src=my.cnf dest=/etc/my.cnf
  notify: restart mysql

