---
- name: set the hostname
  hostname: name=ocean

- name: download virtualmin install script
  tags: webmin
  get_url: >
    url=http://software.virtualmin.com/gpl/scripts/install.sh
    dest=/root/install.sh
    mode=0755

- name: virtualmin install (~10 mins) track via $ sudo tail -f /root/virtualmin-install.log
  shell: ~/install.sh --yes chdir=/root

- name: Virtualmin Post-Installation Wizard
  pause: prompt="virtualmin ready for post-installation, visit - https://{{inventory_hostname}}:10000"
